services:
  dragonfly:
    container_name: dragonfly_chat
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    command: ["--proactor_threads=5", "--maxmemory=3gb"]
    ports:
      - "6379:6379"
    volumes:
      - dragonfly_data:/data
    networks:
      - chat_spring

  scylladb:
    image: scylladb/scylla:latest
    container_name: scylladb_chat
    ports:
      - "9042:9042" # CQL port
      - "9160:9160" # Thrift port (deprecated)
      - "9180:9180" # JMX port (optional)
      - "10000:10000" # Intra-node communication
      - "7001:7001" # Inter-node communication (not strictly needed for single-node, but good practice)
    command: --smp 1 --memory 3G --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - scylla_data_volume:/var/lib/scylla
    restart: unless-stopped
    networks:
      - chat_spring

networks:
  chat_spring:
    driver: bridge

volumes:
  scylla_data_volume: {}
  dragonfly_data: {}
  cassandra_data:
    driver: local
