spring:
  argon:
    saltLength: 16
    hashLength: 32
    parallelism: 1
    memory: 65536
    iterations: 3

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    revoke:
      enabled: true

    jti:
      enabled: true

    header:
      name: Authorization
      prefix: Bearer

    refresh:
      reuse: false
      rotate: true
      max-usage: 1

    exp:
      token: 7
      refresh: 30

    jwt:
      algorithm: HS256
      issuer: chat-api
      audience: chat-client
      clock-skew-seconds: 30
      secret: 747673h4r9fgfgdgyf6t34tgydgy6t43gygyd5fd45c5ds63787324tg387g4fg983g8

  threads:
    virtual:
      enabled: true

  application:
    name: api

server:
  port: 6454

config:
  role:
    roles:
      - USER
      - ADM
      - SUPER_ADM
      - MODERATOR

  front:
    url: http://localhost:5173
    methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: Authorization,Content-Type,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers
    max-age: 3600
    allow-credentials: true
