spring:
  jackson:
    default-property-inclusion: non_null # Não envia campos nulos no JSON
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write-dates-as-timestamps: false # Envia como String ISO-8601, não como números
      indent-output: false # Em produção, mantém o JSON compacto

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    revoke:
      enabled: true

    jti:
      enabled: true

    header:
      name: Authorization
      prefix: Bearer

    refresh:
      reuse: false
      rotate: true
      max-usage: 1

    exp:
      token: 7
      refresh: 30

    jwt:
      algorithm: HS256
      issuer: chat-api
      audience: chat-client
      clock-skew-seconds: 30
      secret: 747673h4r9fgfgdgyf6t34tgydgy6t43gygyd5fd45c5ds63787324tg387g4fg983g8

  threads:
    virtual:
      enabled: true

  application:
    name: api

  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/telegram_clone
    redis:
      host: localhost
      port: 6379

server:
  port: 8888

config:
  front:
    url: http://localhost:5173
    methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: Authorization,Content-Type,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers
    max-age: 3600
    allow-credentials: true
